import Head from 'next/head'
import { Home, Settings, User } from 'lucide-react'

export default function HomePage() {
  return (
    <div className="min-h-screen bg-gray-100">
      <Head>
        <title>Generated Next.js App</title>
        <meta name="description" content="Generated by AI" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto px-4 py-8">
        <div className="max-w-md mx-auto bg-white rounded-lg shadow-md p-6">
          <div className="flex items-center gap-2 mb-4">
            <Home size={24} className="text-blue-500" />
            <h1 className="text-2xl font-bold text-gray-900">
              Welcome to Your Generated App
            </h1>
          </div>
          <p className="text-gray-600 mb-6">
            This is a Next.js application generated by AI. You can customize it as needed.
          </p>
          <div className="flex gap-2">
            <button className="bg-blue-500 hover:bg-blue-600 text-white font-medium py-2 px-4 rounded flex items-center gap-2">
              <Settings size={16} />
              Get Started
            </button>
            <button className="bg-gray-200 hover:bg-gray-300 text-gray-700 font-medium py-2 px-4 rounded flex items-center gap-2">
              <User size={16} />
              Profile
            </button>
          </div>
        </div>
      </main>
    </div>
  )
}